export enum SUCCESS_STATUS {
  CREATED = 201,
  NO_CONTENT = 204,
  PARTIAL_CONTENT = 206,
  SUCCESS = 200,
}
export enum ERROR_STATUS {
  BAD_REQUEST = 400,
  NOT_FOUND = 404,
  UNAUTHORIZED = 401,
}
export enum SERVER_ERROR_STATUS {
  INTERNAL_SERVER_ERROR = 500,
}
